refactor vendor book add pagination
peaksoft-school/ebook-b5 pull request #65
Opened 2022-09-03 13:19 UTC by altyndev

2022-09-03 13:23 UTC, beksultancs requested changes
I don't like this code

2022-09-07 05:40 UTC, beksultancs approved these changes
solve conflicts!

2022-09-07 05:40 UTC, beksultancs commented on pom.xml
> +                    <source>14</source>
bul code deploydo ishtebeit* bul Verdi emne uchun koshtunuz

2022-09-07 05:41 UTC, beksultancs requested changes
need to solve problems

2022-09-07 08:10 UTC, altyndev reviewed
utACK

2022-09-07 08:11 UTC, merged